pool:
  vmImage: 'macOS-10.14'

variables:
  - group: xamarin-ios-pipeline
  - name: solutionPath
    value: '**/*.sln'
  - name: configuration
    value: 'Release'

steps:
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_4_0
  displayName: 'Select the Xamarin SDK version'
  enabled: true

- task: InstallAppleCertificate@2
  inputs:
   certSecureFile: '$(p12FileName)'
   certPwd: '$(p12Password)'
   keychain: 'temp'
   deleteCert: true  

- task: InstallAppleProvisioningProfile@1
  inputs:
   provisioningProfileLocation: 'secureFiles'
   provProfileSecureFile: '$(provisioningProfile)'
   removeProfile: true
   
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
   restoreSolution: '$(solutionPath)'

- task: XamariniOS@2
  inputs:
    solutionFile: '$(solutionPath)'
    configuration: '$(configuration)'
    packageApp: true
    buildForSimulator: false
    runNugetRestore: false
    signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
    signingProvisioningProfileID: '$(APPLE_PROV_PROFILE_UUID)'

- task: AppCenterDistribute@3
  inputs:
    serverEndpoint: 'VSAC'
    appSlug: '$(appSlug)'
    appFile: '$(build.SourcesDirectory)/**/*.ipa'
    releaseNotesOption: 'input'
    releaseNotesInput: 'New ipa release ready.'
    destinationType: 'groups'
    distributionGroupId: '$(distributionGroupId)'
